# basic options
title: Begin Tensorflow
author: Rakesh
email: rakeshiitbbs@gmail.com
description: A wonderful site which describe how to start with tensorflow , with neural network that works in Text analysis
twitter_username: rakeshKM
github_username:  rakeshKM

# Build settings
markdown: kramdown
theme: minima
